---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aeroncache-cluster
  namespace: default
  labels:
    app.kubernetes.io/name: aeroncache-cluster
    app.kubernetes.io/instance: aeroncache-cluster
...