version: '3.8'
services:
  node0:
    build:
      context: cache-cluster
    hostname: cluster0
    shm_size: '1gb'
    networks:
      internal_bus:
        ipv4_address: 172.16.202.2
    environment:
      - CLUSTER_ADDRESSES=172.16.202.2,172.16.202.3,172.16.202.4
      - CLUSTER_NODE=0
      - CLUSTER_PORT_BASE=9000
  node1:
    build:
      context: cache-cluster
    hostname: cluster1
    shm_size: '1gb'
    networks:
      internal_bus:
        ipv4_address: 172.16.202.3
    environment:
      - CLUSTER_ADDRESSES=172.16.202.2,172.16.202.3,172.16.202.4
      - CLUSTER_NODE=1
      - CLUSTER_PORT_BASE=9000
  node2:
    build:
      context: cache-cluster
    hostname: cluster2
    shm_size: '1gb'
    networks:
      internal_bus:
        ipv4_address: 172.16.202.4
    environment:
      - CLUSTER_ADDRESSES=172.16.202.2,172.16.202.3,172.16.202.4
      - CLUSTER_NODE=2
      - CLUSTER_PORT_BASE=9000
  cache-http-client:
    shm_size: '1gb'
    build:
      context: cache-http/http-server-javalin
      dockerfile: ./Dockerfile
    depends_on:
      - node0
      - node1
      - node2
    networks:
      internal_bus:
        ipv4_address: 172.16.202.5
    environment:
      - CLUSTER_ADDRESSES=172.16.202.2,172.16.202.3,172.16.202.4
      - EGRESS_IP=172.16.202.5
  cache-ui:
    build:
      context: cache-ui/nextjs
      dockerfile: ./Dockerfile
    depends_on:
      - node0
      - node1
      - node2
      - cache-http-client
    networks:
      internal_bus:
        ipv4_address: 172.16.202.6
    ports:
      - 3000:3000
    environment:
      - AERON_CACHE_API=http://172.16.202.5:7070/api/v1
networks:
  internal_bus:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.driver.mtu: 9000
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
        - subnet: "172.16.202.0/24"