version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      internal_bus:
        ipv4_address: 172.16.202.7
    depends_on:
      - cache-ui
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-aeron-cache
    ports:
      - 9090:9090
    networks:
      internal_bus:
        ipv4_address: 172.16.202.8
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-aeron-cache
    ports:
      - 8080:8080
    networks:
      internal_bus:
        ipv4_address: 172.16.202.9
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - cache-ui
#  grafana:
#    image: grafana/grafana
#    environment:
#      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
#      GF_AUTH_ANONYMOUS_ENABLED: "true"
#      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
#      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
#      GF_AUTH_DISABLE_LOGIN_FORM: "true"
#    volumes:
#      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
#    ports:
#      - "9100:3000"
#    networks:
#      internal_bus:
#        ipv4_address: 172.16.202.10
  node0:
    build:
      context: cache-cluster
    hostname: cluster0
    shm_size: '1gb'
    networks:
      internal_bus:
        ipv4_address: 172.16.202.2
    environment:
      - CLUSTER_ADDRESSES=node0,node1,node2
      - CLUSTER_NODE=0
      - CLUSTER_PORT_BASE=9000
      - OTEL_SERVICE_NAME=aeron-cache-cluster-node
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - CACHE_MODE=RAFT
      - CACHE_DATA_DIR=/tmp/data
    volumes:
      - ./data/node0:/tmp/data
  node1:
    build:
      context: cache-cluster
    hostname: cluster1
    shm_size: '1gb'
    networks:
      internal_bus:
        ipv4_address: 172.16.202.3
    environment:
      - CLUSTER_ADDRESSES=node0,node1,node2
      - CLUSTER_NODE=1
      - CLUSTER_PORT_BASE=9000
      - OTEL_SERVICE_NAME=aeron-cache-cluster-node
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - CACHE_MODE=RAFT
      - CACHE_DATA_DIR=/tmp/data
    volumes:
      - ./data/node1:/tmp/data
  node2:
    build:
      context: cache-cluster
    hostname: cluster2
    shm_size: '1gb'
    networks:
      internal_bus:
        ipv4_address: 172.16.202.4
    environment:
      - CLUSTER_ADDRESSES=node0,node1,node2
      - CLUSTER_NODE=2
      - CLUSTER_PORT_BASE=9000
      - OTEL_SERVICE_NAME=aeron-cache-cluster-node
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - CACHE_MODE=RAFT
      - CACHE_DATA_DIR=/tmp/data
    volumes:
      - ./data/node2:/tmp/data
  cache-http-client:
    shm_size: '1gb'
    build:
      context: cache-http/http-server-javalin
      dockerfile: ./Dockerfile
    depends_on:
      - node0
      - node1
      - node2
    networks:
      internal_bus:
        ipv4_address: 172.16.202.5
    ports:
      - 7070:7070
    environment:
      - CLUSTER_ADDRESSES=node0,node1,node2
      - EGRESS_IP=172.16.202.5
      - OTEL_SERVICE_NAME=aeron-cache-http
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_JAVAAGENT_LOGGING=none
      - CACHE_MODE=RAFT
  cache-ws-client:
    shm_size: '1gb'
    build:
      context: cache-ws/ws-server-javalin
      dockerfile: ./Dockerfile
    depends_on:
      - node0
      - node1
      - node2
    networks:
      internal_bus:
        ipv4_address: 172.16.202.11
    ports:
      - 7071:7071
    environment:
      - CLUSTER_ADDRESSES=node0,node1,node2
      - EGRESS_IP=172.16.202.5
      - OTEL_SERVICE_NAME=aeron-cache-ws
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_JAVAAGENT_LOGGING=none
      - CACHE_MODE=RAFT
  cache-sse-client:
    shm_size: '1gb'
    build:
      context: cache-sse/sse-server-jooby
      dockerfile: ./Dockerfile
    depends_on:
      - node0
      - node1
      - node2
    networks:
      internal_bus:
        ipv4_address: 172.16.202.12
    ports:
      - 7072:7072
    environment:
      - CLUSTER_ADDRESSES=node0,node1,node2
      - EGRESS_IP=172.16.202.5
      - OTEL_SERVICE_NAME=aeron-cache-ws
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_JAVAAGENT_LOGGING=none
      - CACHE_MODE=RAFT
      - REQUEST_PUB_HOST=node0
  cache-gateway-client:
    shm_size: '1gb'
    build:
      context: cache-aeron-gateway/aeron-gateway-server
      dockerfile: ./Dockerfile
    depends_on:
      - node0
      - node1
      - node2
    networks:
      internal_bus:
        ipv4_address: 172.16.202.13
    ports:
      - 7073:7073
      - 7075:7075/udp
      - 7076:7076/udp
    environment:
      - CLUSTER_ADDRESSES=node0,node1,node2
      - EGRESS_IP=172.16.202.5
      - OTEL_SERVICE_NAME=aeron-cache-gateway
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_JAVAAGENT_LOGGING=none
      - CACHE_MODE=RAFT
      - GATEWAY_REQUEST_ENDPOINT=0.0.0.0:7075
      - GATEWAY_RESPONSE_CONTROL_ENDPOINT=172.16.202.13:7076
  cache-ui:
    build:
      context: cache-ui/nextjs
      dockerfile: ./Dockerfile
    depends_on:
      - node0
      - node1
      - node2
      - cache-http-client
    networks:
      internal_bus:
        ipv4_address: 172.16.202.6
    ports:
      - 3000:3000
    environment:
      - AERON_CACHE_API=http://cache-http-client:7070/api/v1
      - OTEL_SERVICE_NAME=aeron-cache-ui
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
networks:
  internal_bus:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.driver.mtu: 9000
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
        - subnet: "172.16.202.0/24"