version: '3.5'
services:
  cache-cluster:
    container_name: aeron-cache-cluster
    build:
      context: cache-cluster
      dockerfile: ./Dockerfile
    shm_size: '512m'
    networks:
      internal_bus:
        ipv4_address: 172.16.202.2
  cache-client:
    shm_size: '512m'
    build:
      context: cache-client
      dockerfile: ./Dockerfile
    depends_on:
      - cache-cluster
    networks:
      internal_bus:
        ipv4_address: 172.16.202.3
networks:
  internal_bus:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.driver.mtu: 9000
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
        - subnet: "172.16.202.0/24"