apiVersion: v1
kind: Service
metadata:
  name: {{ include "aeroncache-monolith.fullname" . }}
  labels:
    {{- include "aeroncache-monolith.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.websocketEnabled }}
    - port: {{ .Values.ports.ws }}
      targetPort: ws
      protocol: TCP
      name: ws
    {{- end }}
    {{- if .Values.sseEnabled }}
    - port: {{ .Values.ports.sse }}
      targetPort: sse
      protocol: TCP
      name: sse
    {{- end }}
    - port: {{ .Values.ports.clusterTools }}
      targetPort: cluster-tools
      protocol: TCP
      name: cluster-tools
  selector:
    {{- include "aeroncache-monolith.selectorLabels" . | nindent 4 }}
