apiVersion: v1
kind: Service
metadata:
  name: {{ include "aeronCacheChart.fullname" . }}
  labels:
    {{- include "aeronCacheChart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    {{- include "aeronCacheChart.selectorLabels" . | nindent 4 }}
