apiVersion: v1
kind: ConfigMap
metadata:
  name: aeroncache-sse-config
  namespace: {{ .Release.namespace }}
data:
  DNS_DELAY: "true"
  CACHE_MODE: {{ tpl .Values.cacheMode . | quote }}
  CLUSTER_ADDRESSES: {{ tpl .Values.clusterAddresses . | quote }}
  {{- if .Values.ephemeralRequestEndpoint }}
  EPHEMERAL_REQUEST_ENDPOINT: {{ tpl .Values.ephemeralRequestEndpoint . | quote }}
  EPHEMERAL_RESPONSE_CONTROL_ENDPOINT: {{ tpl .Values.ephemeralResponseControlEndpoint . | quote }}
  AERON_IMAGE_LIVENESS_TIMEOUT_SECONDS: {{ .Values.aeronImageLivenessTimeoutSeconds | default "2" | quote }}
  {{- end }}
  {{- if .Values.corsAllowedOrigins }}
  CORS_ALLOWED_ORIGINS: {{ tpl .Values.corsAllowedOrigins . | quote }}
  {{- end }}
  {{- if .Values.idleStrategy }}
  IDLE_STRATEGY: {{ tpl .Values.idleStrategy . | quote }}
  {{- end }}
  {{- printf "environments/configmap.%s.yaml" .Values.env | .Files.Get | nindent 2 }}
