apiVersion: v1
kind: Service
metadata:
  name: {{ include "aeroncache-sse.fullname" . }}
  labels:
    {{- include "aeroncache-sse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7072
      protocol: TCP
      name: http
  selector:
    {{- include "aeroncache-sse.selectorLabels" . | nindent 4 }}
