install:
	helm install -n aeroncache aeroncache-ui-nextjs -f values.yaml .

upgrade:
	helm upgrade -n aeroncache aeroncache-ui-nextjs -f values.yaml

uninstall:
	helm uninstall -n aeroncache aeroncache-ui-nextjs