apiVersion: v1
kind: Service
metadata:
  name: {{ include "aeroncache-ephemeral.fullname" . }}
  labels:
    {{- include "aeroncache-ephemeral.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    {{- include "aeroncache-ephemeral.selectorLabels" . | nindent 4 }}
