apiVersion: v1
kind: ConfigMap
metadata:
  name: aeroncache-singlenode-config
  namespace: {{ .Release.Namespace }}
data:
  HTTP_RESPONSE_PUB_HOST: aeroncache-http-javalin
  WS_RESPONSE_PUB_HOST: aeroncache-ws-javalin
  SSE_RESPONSE_PUB_HOST: aeroncache-sse-jooby
  DNS_DELAY: "true"
  CACHE_MODE: {{ .Values.cacheMode | quote }}
  CLUSTER_ADDRESSES: "aeroncache-singlenode-0.aeroncache-singlenode.{{ .Release.Namespace }}.svc.cluster.local,aeroncache-singlenode-1.aeroncache-singlenode.{{ .Release.Namespace }}.svc.cluster.local,aeroncache-singlenode-2.aeroncache-singlenode.{{ .Release.Namespace }}.svc.cluster.local"
  {{ printf "environments/configmap.%s.yaml" .Values.env | .Files.Get | indent 2 }}
