---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aeroncache-http-near
  namespace: default
  labels:
    app.kubernetes.io/name: aeroncache-http-near
    app.kubernetes.io/instance: aeroncache-http-near
...