---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aeroncache-ui-nextjs
  namespace: default
  labels:
    app.kubernetes.io/name: aeroncache-ui-nextjs
    app.kubernetes.io/instance: aeroncache-ui-nextjs
...