apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-multi-env-configmap
  namespace: {{ .Values.namespace }}
data:
  DNS_DELAY: "true"
  CLUSTER_ADDRESSES: "aeroncache-cluster-0.aeroncache-cluster.default.svc.cluster.local,aeroncache-cluster-1.aeroncache-cluster.default.svc.cluster.local,aeroncache-cluster-2.aeroncache-cluster.default.svc.cluster.local"
  {{ printf "environments/configmap.%s.yaml" .Values.env | .Files.Get | indent 2 }}