apiVersion: v1
kind: Service
metadata:
  name: {{ include "aeroncache-http-clustertools.fullname" . }}
  labels:
    {{- include "aeroncache-http-clustertools.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "aeroncache-http-clustertools.fullname" . }}-0

