apiVersion: v1
kind: ConfigMap
metadata:
  name: aeroncache-gateway-config
  namespace: {{ .Release.namespace }}
data:
  DNS_DELAY: "true"
  CACHE_MODE: {{ tpl .Values.cacheMode . | quote }}
  CLUSTER_ADDRESSES: {{ tpl .Values.clusterAddresses . | quote }}
  REQUEST_PUB_HOST: {{ tpl .Values.requestPubHost . | quote }}
  GATEWAY_REQUEST_ENDPOINT: {{ tpl .Values.gatewayRequestEndpoint . | quote }}
  GATEWAY_RESPONSE_CONTROL_ENDPOINT: {{ tpl .Values.gatewayResponseControlEndpoint . | quote }}
  {{ printf "environments/configmap.%s.yaml" .Values.env | .Files.Get | indent 2 }}
