apiVersion: v1
kind: Service
metadata:
  name: {{ include "aeroncache-gateway.fullname" . }}
  labels:
    {{- include "aeroncache-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.requestPort }}
      targetPort: {{ .Values.service.requestPort }}
      protocol: UDP
      name: aeron-req
    - port: {{ .Values.service.responseControlPort }}
      targetPort: {{ .Values.service.responseControlPort }}
      protocol: UDP
      name: aeron-resp
  selector:
    {{- include "aeroncache-gateway.selectorLabels" . | nindent 4 }}
