apiVersion: v1
kind: Pod
metadata:
  name: aeroncache-http
  labels:
    run: aeroncache-http
spec:
  serviceAccountName: aeroncache-http
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 1Gi
      name: shm
  containers:
    - name: aeroncache-http
      image: docker.io/library/aeroncache-http
      imagePullPolicy: Never
      ports:
      - containerPort: 7070
        protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm