apiVersion: v1
kind: Service
metadata:
  labels:
    run: aeroncache-http
  name: aeroncache-http
  namespace: default
spec:
  clusterIP: 10.106.206.100
  clusterIPs:
  - 10.106.206.100
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    run: aeroncache-http
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}