---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aeroncache-http
  namespace: default
  labels:
    app.kubernetes.io/name: aeroncache-http
    app.kubernetes.io/instance: aeroncache-http
...