apiVersion: v1
kind: Service
metadata:
  labels:
    run: aeroncache-http
  name: aeroncache-http
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 7070
    nodePort: 30000
    protocol: TCP
    targetPort: 7070
  selector:
    run: aeroncache-http
  sessionAffinity: None
  type: NodePort