install:
	helm install -n aeroncache aeroncache-http-clustertools -f values.yaml .

upgrade:
	helm upgrade -n aeroncache aeroncache-http-clustertools -f values.yaml

uninstall:
	helm uninstall -n aeroncache aeroncache-http-clustertools