install:
	helm install -n aeroncache aeroncache-sse-jooby -f values.yaml .

upgrade:
	helm upgrade -n aeroncache aeroncache-sse-jooby -f values.yaml

uninstall:
	helm uninstall -n aeroncache aeroncache-sse-jooby