apiVersion: v1
kind: Service
metadata:
  name: aeroncache-http-clustertools
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: aeroncache-http-clustertools-0
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070