---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aeroncache-http-clustertools
  namespace: default
  labels:
    app.kubernetes.io/name: aeroncache-http-clustertools
    app.kubernetes.io/instance: aeroncache-http-clustertools
...