install:
	helm install -n aeroncache aeroncache-ws-javalin -f values.yaml .

upgrade:
	helm upgrade -n aeroncache aeroncache-ws-javalin -f values.yaml

uninstall:
	helm uninstall -n aeroncache aeroncache-ws-javalin